name: CI Action

on:
  pull_request:
    branches:
      - main

jobs:
  ci-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Test action email
        uses: ./
        with:
          api-key: ${{ secrets.NOTIFY_API_KEY }}
          personalisation: |
            {"subject": "Test subject", "body": "Test body"}
          recipient: cds-test-user@cds-snc.ca
          template-id: ${{ secrets.EMAIL_TEMPLATE_ID }}

      - name: Test action sms
        uses: ./
        with:
          api-key: ${{ secrets.NOTIFY_API_KEY }}
          message-type: sms
          recipient: "+447900900123"
          template-id: ${{ secrets.SMS_TEMPLATE_ID }}
